### ISSUE TITLE
userEvent.type puts the first typed character at the end of an input

### ISSUE THREAD

**Issue by AndreyChernykh** [testing-library/user-event#477] opened 2020-10-28 18:59 UTC
- `@testing-library/react`: "^10.4.5",
- `@testing-library/user-event`: "^12.1.10",

Problem description:

```js
import userEvent from '@testing-library/user-event';
import { render, screen } from '@testing-library/react';

it('textarea input', () => {
    render(<textarea />);

    userEvent.type(screen.getByRole('textbox'), 'Hello, World!');
    expect(screen.getByRole('textbox')).toHaveValue('Hello, World!');
}
```

```
    Expected the element to have value:
      Hello, World!
    Received:
      ello, World!H
```

For some reason, the first input symbol goes to the end of the string.

**Comment by nickmccurdy** [comment] 2020-10-29 09:43
I suspect this is an issue with an outdated version jsdom and therefore a duplicate of #402. You can fix this by using [mCreate React App 4](https://github.com/facebook/create-react-app/releases/tag/v4.0.0) or [jest-environment-jsdom-16](https://www.npmjs.com/package/jest-environment-jsdom-sixteen).

**Closed** 2020-10-29 09:43 UTC
Labels: duplicate, jsdom
