### ISSUE TITLE
Touch events not firing using userEvent.pointer

### ISSUE THREAD

**Issue by ernestostifano** [testing-library/user-event#1095] opened 2023-01-20 09:55 UTC
### Reproduction example

https://codesandbox.io/s/upbeat-morning-lqw00o

### Prerequisites

1. Render any element and attach an event listener to the 'touchstart' event.
2. Create a simple test with Jest.
3. Call `userEvent.pointer({keys: '[TouchA>]', target: 'target element here'})`.
4. Make some assertion to detect event fired (change state inside component, like a text, and read it here).

### Expected behavior

I expect the 'touchstart' event to be fired.

### Actual behavior

A 'mousedown' event is fired instead.

### User-event version

14.4.3

### Environment

See linked Codesandbox.

### Additional context

N/A.

**Comment by ph-fritsche** [comment] 2023-01-20 14:19
Duplicate of https://github.com/testing-library/user-event/issues/880

**Closed by ph-fritsche** 2023-01-20 14:19 UTC
Labels: bug, needs assessment

**Comment by TheMetaverseEngineer** [comment] 2023-03-31 12:34
Isn't this fixed yet? I want to use touch event and move it from a coord to another coord and my test just keeps failing. But mouse events work pretty well, though.
