### ISSUE TITLE
Add option to disable special handling of '[]' and '{}' in keyboard input

### ISSUE THREAD

**Issue by joeltine** [testing-library/user-event#840] opened 2022-01-21 15:45 UTC
- `@testing-library/user-event` version: 13.5.0

- Testing Framework and version: Jasmine 3.10.1

I'm writing some tests to validate user typed text input is valid JSON. This is making writing validating strings to be typed quite difficult:

Consider this code that does input validation on each keyUp event:

```
const validInputs = ['[[]', '[[1,2,3] ', '[["test", "me"]', '[[[[]'];
const arrayInput = getByPlaceholderText('input array'); // input[type="text"] field.

for (let valid of validInputs) {
      await userEvent.clear(arrayInput);
      await userEvent.type(arrayInput, valid);
      expect(arrayInput).withContext(`input="${arrayInput.value}"`).toBeValid();
}
```

Note the 'validInputs' array. It's a bit confusing that only the opening bracket needs to be escaped. Then if you want to do any type of nested array, e.g., to emulate typing "[[]]", it (afaict) isn't even possible. I've tried lots of variations but it doesn't seem to accept the first nested bracket: `Error: Expected key descriptor but found "[" in "[[[[]]"`.

**Comment by ph-fritsche** [comment] 2022-01-22 15:28
The feature request looks like a duplicate of #586 .

`await userEvent.type(screen.getByRole('textbox'), '[[[[]]')` works as expected in [v14](https://testing-library.com/docs/user-event/intro/).

**Closed by ph-fritsche** 2022-01-22 15:28 UTC
