### ISSUE TITLE
userEvent.type(input, 'text') consistently shuffles the input

### ISSUE THREAD

**Issue by jmyrland** [testing-library/user-event#391] opened 2020-06-26 09:18 UTC
- `@testing-library/user-event` version: 12.0.11
- Testing Framework and version: jest@24.9.0
  
- DOM Environment: jsdom@14.0.0 (via `jest-environment-jsdom-fourteen`)
  

I'm having some issues with the following test-snippet (copied from the readme with some minor modification):

```javascript
test('type', () => {
  render(<textarea />);

  userEvent.type(screen.getByRole('textbox'), 'hey');
  expect(screen.getByRole('textbox')).toHaveValue('hey');
});
```

When I run this, it fails with the following output:

![image](https://user-images.githubusercontent.com/837651/85841153-f7997800-b79d-11ea-8215-7e376537f9ab.png)

Whatever text i input, it chucks the first input-character at the end, (i.e. `123` -> `231`).

I'm guessing this is not the expected outcome - or if so, what am I missing? 😁 

I'm using `fireEvent.change(screen.getByRole('textbox'), { target: { value: 'hey' } })` as a workaround for now.

**Comment by kentcdodds** [comment] 2020-06-26 14:33
I have reproduced this issue: https://codesandbox.io/s/pedantic-maxwell-wu50t?file=/src/__tests__/index.js

I'm guessing it's something odd with React because we absolutely have tests for this:

https://github.com/testing-library/user-event/blob/26d246269058228a8255aa1ce8b3e438aa7ad3e2/src/__tests__/type.js#L109-L144

I'm not sure what the problem is, but if someone wants to investigate and figure out what we're doing wrong that would be great.

**Comment by jmyrland** [comment] 2020-06-26 14:42
I just noticed this:

> @testing-library/user-event@12.0.11" has unmet peer dependency "@testing-library/dom@>=7.16.0".

Might this be related?

**Comment by lourenci** [comment] 2020-06-26 14:53
I can take a look at this later.

**Comment by nickmccurdy** [comment] 2020-06-26 15:04
[The sandbox](https://codesandbox.io/s/pedantic-maxwell-wu50t?file=/src/__tests__/index.js) depends on Jest DOM, doesn't have peer dependency warnings for it, and still fails.

**Comment by nickmccurdy** [comment] 2020-06-29 21:03
This bug was introduce in #322 (version 11.3.1)

**Comment by marcosvega91** [comment] 2020-06-29 21:28
this issue is like #346. The problem is that when the `textarea` has no default value both `selectionStart` and `selectionEnd` are `undefined`. I have tried locally  in the past but this issue not happens. It happens only in codesandbox. 

We can add a check at the beginning of `type` function, but it's very odd

```diff
diff --git a/src/type.js b/src/type.js
index 0bee11e..632dc97 100644
--- a/src/type.js
+++ b/src/type.js
@@ -65,6 +65,15 @@ async function typeImpl(
     }
     return value
   }
+
+  if (
+    typeof currentElement().selectionStart === 'undefined' ||
+    typeof currentElement().selectionEnd === 'undefined'
+  ) {
+    currentElement().selectionStart = 0
+    currentElement().selectionEnd = 0
+  }
+
   const setSelectionRange = ({newValue, newSelectionStart}) => {
     // if we *can* change the selection start, then we will if the new value
     // is the same as the current value (so it wasn't programatically changed
```

**Comment by kentcdodds** [comment] 2020-06-29 22:10
Is there any way we can alter the code in other places so we don't actually set the selection range?

**Comment by nickmccurdy** [comment] 2020-06-30 04:13
Unfortunately I think it'll be hard to test this out until we can reproduce it locally. As far as I'm aware this bug only reproduces on Code Sandbox, but I don't think it supports linking packages.

**Comment by nickmccurdy** [comment] 2020-07-10 02:24
This issue and #346 have been fixed in JSDOM, but Code Sandbox's Jest support is still hard coded to use JSDOM 4.0.0, which doesn't have the fix: https://github.com/codesandbox/codesandbox-client/pull/1812/files#diff-3fcdeb2de813a974b29d8610b234c7f2R51

There would be two ways to solve this:
1. Patch Code Sandbox so it's not hard coded to JSDOM 4.0.0
2. Patch our updates in #322 so it still works in JSDOM 4.0.0

**Comment by kentcdodds** [comment] 2020-07-10 03:54
I think codesandbox will be making an effort to address some of these issues soon.

**Comment by nickmccurdy** [comment] 2020-07-10 03:59
Do we want to close this instead of patching? I've opened codesandbox/codesandbox-client#4530 for now.

**Comment by kentcdodds** [comment] 2020-07-10 04:25
Yeah, I don't want to worry about supporting old versions of JSDOM

**Closed by kentcdodds** 2020-07-10 04:25 UTC
Labels: bug, help wanted, jsdom

**Comment by marcosvega91** [comment] 2020-08-08 17:04
The issue has been resolved on `codesandbox` so [this](https://codesandbox.io/s/pedantic-maxwell-wu50t?file=/src/__tests__/index.js) example is now working 😄

**Comment by lammypham** [comment] 2020-08-18 18:49
I can get this issue resolved on the codesandbox, but when i download the project from codesandbox and run locally, i still get this issue.

Is this still expected? Thanks in advance.

**Comment by nickmccurdy** [comment] 2020-08-21 08:14
[Code Sandbox has now pinned JSDOM 16.](https://github.com/codesandbox/codesandbox-client/pull/4539) Your dependencies may not have it installed however. Try upgrading Jest first. If that doesn't help or you're using CRA (which doesn't let you upgrade Jest without ejecting), you can install `jest-environment-jsdom-sixteen`.

**Comment by imnotteixeira** [comment] 2020-12-07 18:45
Hey guys, just stumbled on this. Is there a solution for this, or do I just need to install and set `jest-environment-jsdom-sixteen`?

**Comment by nickmccurdy** [comment] 2020-12-08 01:25
You can check your jsdom version with `npm ls jsdom` or `yarn why jsdom` (make sure to use the same package manager as your project). If it's not 16 you'll likely need `jest-environment-jsdom-sixteen`.

**Comment by imnotteixeira** [comment] 2020-12-08 09:28
Thanks @nickmccurdy, it solved this issue. Currently having the issue of #387, but that's another problem...
