### ISSUE TITLE
Type into text field generate a Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [testing-library/user-event#849] opened 2022-02-08 09:32 UTC
- `@testing-library/user-event` version: ^14.0.0-beta

- Testing Framework and version:
  jest: 26.6.3
- DOM Environment:
  jsdom

Relevant code or config

```javascript
      const { getAllByTestId } = createWrapper();
      await flushPromises();

      const dummyText = chance.string({ length: 50, alpha: true });

      const field = getAllByTestId(<someid>);
      // Input and Label have the same id
      await userEvent.clear(field[0]);
      await userEvent.type(field[0], dummyText); // <-- Here the error will be thrown
```

What you did:

I searched for a testId cleared the field to get rid of text that might already been in there. Type 50 characters to check that maxlength 40 works as expected for the user.

What happened:

The input triggered a cascade of clicks in an endless loop

```at Object.<anonymous>.behavior.click (node_modules/@testing-library/user-event/dist/index.cjs:1387:11)```

Problem description:

I used an inputelement as target, I don't know why the label is looked up and a trigger is fired, and I don't know why there seems to be a loop.

Suggested solution:

Break the infinite loop

**Comment by sschneider-ihre-pvs** [comment] 2022-02-08 09:38
![image](https://user-images.githubusercontent.com/86342787/152959663-c202a74e-29eb-4394-a26a-b0cc2b38abdf.png)

**Comment by ph-fritsche** [comment] 2022-02-08 09:58
Could you please provide a reproduction or the component under test?

This is probably a duplicate of #848 which also lacks a reproduction.

**Comment by sschneider-ihre-pvs** [comment] 2022-02-08 10:15
It is a simple quasar component wich pretty much has a label and input
```pug
q-input(
  v-model="fieldValue"
  label="label"
  dense
  hide-bottom-space
  maxlength="40"
  counter
)
```

**Comment by sschneider-ihre-pvs** [comment] 2022-02-08 10:18
and yes it looks very similar to #848 
![image](https://user-images.githubusercontent.com/86342787/152967183-465056f8-6b77-4b16-bbd4-f97bc0d93c00.png)

**Comment by sschneider-ihre-pvs** [comment] 2022-02-08 10:23
```html
<div class="q-field__control-container col relative-position row no-wrap q-anchor--skip">
  <input class="q-field__native q-placeholder" tabindex="0" aria-label="label" id="f_aa825cbe-9cbd-490e-b61a-e10950428677" maxlength="40" type="text">
</div>
```
in my case there is no wrapping label tag

**Closed** 2022-02-08 11:09 UTC
Labels: bug
