### ISSUE TITLE
Select multiple options doesn't send correct values in “onChange” callback?

### ISSUE THREAD

**Issue by freewind** [testing-library/user-event#187] opened 2019-11-24 08:15 UTC
I have a question (or found an issue?) about `userEvent.selectOptions`, and firstly asked in stackoverflow: 

https://stackoverflow.com/questions/58948791/testing-with-testing-library-user-event-to-select-multiple-options-doesnt-send

But I can't get any answers there so I want to post it here for help. Thanks

**Comment by mikeyshing88** [comment] 2019-11-26 13:13
I am facing the same issue - haven't found a solution as of yet neither

**Comment by djalmaaraujo** [comment] 2020-02-26 00:41
I am also facing this issue. Are you guys using a blank option? This is why. If you add a disabled attribute to the option with the `value=""` it will always get the value from the first `<option>` with a value.

But it's a valid bug.

**Comment by Gpx** [comment] 2020-04-23 11:28
It seems some sort of problem with `selectedOptions` that doesn't get updated, I'm not sure why since a similar bug had been reported already https://github.com/testing-library/dom-testing-library/issues/115

A workaround would be to use `options` instead of `selectedOptions` and filter by `selected`:

```js
const selectedOptions = Array.from(event.target.options).filter(
  (option) => option.selected
);
```

**Comment by nickmccurdy** [comment] 2020-06-09 00:27
I can confirm that @freewind's and @djalmaaraujo's issues are fixed by updating Jest to the latest version. It appears this was just a bug with an older bundled version of JSDOM, not `user-event`. This can be closed.

**Comment by kentcdodds** [comment] 2020-06-09 02:29
Thanks @nickmccurdy!

**Closed** 2020-06-09 02:29 UTC
Labels: bug

**Comment by kentcdodds** [comment] 2020-06-09 02:30
@all-contributors please add @nickmccurdy for projectManagement and question
