### ISSUE TITLE
userEvent.type - Only typing in the first letter of my provided input on React 17

### ISSUE THREAD

**Issue by seanmcquaid** [testing-library/user-event#533] opened 2020-12-24 01:54 UTC
- `@testing-library/user-event` version: 12.6.0

- Testing Framework and version: Jest 26.6.3
  
- DOM Environment: jsdom 16.4.0
  

What you did: I set up a test to check the input value after typing with text of "Input"

What happened: The input value in the test was only set to "I"

Reproduction repository: https://codesandbox.io/s/peaceful-surf-fedc7?file=/src/App.spec.js

Problem description: The userEvent is not firing off completely and is only typing the first letter of my provided input on React 17. This is leading to cases where I can't write complete tests currently. I am not totally sure if this will help but there are similar issues with fireEvent as well. 

Suggested solution:

**Comment by ph-fritsche** [comment] 2020-12-24 09:15
This one is tricky.

Remember variables are bound to their declaration. Properties are resolved when the expression is executed.
```js
  const onChange = (event) => {
    setState((prevState) => ({
      ...prevState,
      // event is bound - event.target.value is resolved when the reducer is executed
      [event.target.name]: event.target.value
    }));
  };

  // this one works
  const onChange = (event) => {
    const value = event.target.value
    setState((prevState) => ({
      ...prevState,
      [event.target.name]: value
    }));
  };
```

Now React hooks are no language constructs and you can use them in any way, but I guess it doesn't make life easier.
While `setState` with a reducer works, I suggest you use `useReducer` for that.

```js
  const [state, change] = useReducer(
    (prevState, newProps) => ({
      ...prevState,
      ...newProps
    }),
    {}
  );
  const onChange = (event) => {
    change({
      [event.target.name]: event.target.value
    });
  };
```

Regarding the issue, I think it should be closed as out of scope, but someone else should have a look at this first.
While it does behave differently in the browser, the reasons lie deep down in how fireEvent creates the Event on an element controlled by React. I'm not sure there is an easy way to fix this.

**Comment by seanmcquaid** [comment] 2020-12-24 14:12
I genuinely appreciate you taking a lot at this and providing a solution! I didn't consider creating a seperate variable for the value when I was experimenting with different possible solutions. I am fine with this being closed out but could also see other people with similar code run into this issue moving forward. As I referenced in the issue, this also happens with fireEvent.change so you definitely are spot on with your assessment.

**Closed** 2021-01-05 15:18 UTC

**Comment by adamchenwei** [comment] 2021-11-04 18:03
why this is closed? I still observe the same bug till this day though

**Comment by adamchenwei** [comment] 2021-11-04 18:03
@ph-fritsche ☝️

**Comment by ph-fritsche** [comment] 2021-11-04 19:55
@adamchenwei This was closed because there was no issue with this library.
If you feel like you have a similar issue, please file a new issue with a reproduction example at codesandbox and we'll look into it.

**Comment by andreasdjs** [comment] 2021-11-05 22:39
@ph-fritsche 

I had the same problem and your solution saved the day for me, thank you! 👍 

Like you wrote, the value had to be resolved before putting it inside the prevState thingy, like this:
`const { value } = event.target;`

**Comment by kodos18** [comment] 2021-11-16 12:23
> why this is closed? I still observe the same bug till this day though. do we have a better way to allow typing multiple letters? just one letter is not doing well for full testing of things like TextField for materialUI.
> *NOTE: I am using useReducer, but not useContext nor setState or useState in the form that I was testing on with RTL

i have to agree. i don't understand why this is not a bug. we have to change our code so that the test library works, when it works fine in the browser.
i really feel that this should be addressed.

**Comment by ph-fritsche** [comment] 2021-11-16 13:32
> i don't understand why this is not a bug. 

As mentioned earlier, this one is indeed tricky and can be confusing if you don't know yet how the browser applies changes to the DOM on user input and how React implements the "control" of a DOM element.

> we have to change our code so that the test library works, when it works fine in the browser.

Do you know that it works fine in the browser? Or did you just observe that it happens to work?

If your code does not work as expected with our testing tools, this might be because:
1. It is a bug on our end. We'd like to change this, so please file an issue and provide a reproduction example that demonstrates what should happen in the DOM and what does happen in the DOM when using this library.
2. You're beyond the constraints of simulating how a browser alters the DOM and dispatches *trusted* events on user input in ways that are not programmatically accessible. We'd like to change this, but we can't.
3. And this is the most common case: Your code is brittle. It happens to work, but it does not work reliably according to specs and/or living standard. You happened to write/inherit code that produced the desired result, but either the implementation relies on a specific environment or it relies on specific input and the input you assumed you provided is different from the input you did provide.
