### ISSUE TITLE
userEvent.type backspace does not work

### ISSUE THREAD

**Issue by lanmonster** [testing-library/user-event#564] opened 2021-02-23 15:02 UTC
- `@testing-library/user-event` version: "^12.1.10"

- Testing Framework and version: it's a default CRA project and react-scripts is version 4.0.1. not sure what version of jest it uses...
  
- DOM Environment: jsdom "@testing-library/jest-dom": "^5.11.4",
  

Relevant code or config

```javascript
it('test', () => {
    render(<App />)

    userEvent.type(document.body, "{backspace}")

    //error
})
```

What you did: trying to test behavior when backspace is pressed

What happened: backspace event is not fired and there is an error saying "cannot read length of undefined"

![image](https://user-images.githubusercontent.com/3748720/108862054-bbc0e780-75a4-11eb-8631-4a94354362df.png)

Reproduction repository:

https://codesandbox.io/s/gracious-noyce-dso6z?file=/src/__tests__/test.js

Problem description: backspace event does not appear to fire

Suggested solution: 🤷

**Comment by ph-fritsche** [comment] 2021-02-23 15:44
Thanks for the report :)

Duplicate of #481 .

Will be fixed with #521, but I guess this will take some time.
Until then, you can not use `userEvent.type` to type on non-editable elements.

**Closed by ph-fritsche** 2021-02-23 15:44 UTC
