### ISSUE TITLE
TypeError: userEvent.click is not a function

### ISSUE THREAD

**Issue by bamthomas** [testing-library/user-event#757] opened 2021-10-21 13:09 UTC
- `@testing-library/user-event` version:
13.5.0

- Testing Framework and version:
jest 27.3.1
  
- DOM Environment:
jest-dom 5.14.0
@testing-library/dom 7.31.2

Note that there is also a dependency coming from @testing-library/svelte that is linked to the 7.0.3 version
```
├─ @testing-library/svelte@3.0.3
│  └─ @testing-library/dom@^7.0.3
```

Relevant code or config

```javascript
userEvent.click(button)
```
We launch tests with the line : 
```shell
NODE_OPTIONS=--experimental-vm-modules jest src --config jest.config.json
```

What you did:

```
$ npm init svelte@next
// select typescript
npx apply rossyman/svelte-add-jest
// use typescript
npx svelte-add@latest scss
yarn add -D @testing-library/user-event
```

What happened:

When using function from userEvent it seems that it is not defined in the userEvent namespace.
We have the following error : 

```shell
    TypeError: userEvent.click is not a function

      20 |     test('should increment counter', () => {
      21 |       const button = renderedComponent.container.querySelector('.btn-increment');
    > 22 |       userEvent.click(button);
         |                 ^
      23 |       userEvent.click(button);
      24 |       expect(renderedComponent.getByText('2')).toBeInTheDocument();
      25 |     });

      at Object.<anonymous> (src/routes/index-dom.spec.ts:22:17)
```

Reproduction repository:

https://github.com/iroco-co/svelte-add-jest-userEvent

Problem description:

It seems to me (but I'm not experienced enough in typescript/ESM subtilities) that it is linked to the use of ESM.
Before using this mode, the tests with user-event were green. Pb was that we needed to use `$app/env` . When we mapped this into jest config to `.svelte-kit/dev/runtime/app/env.ts` we had SSR `import.meta` errors.

So we tried to use rossyman jest add recipe that was addressing this issue. It worked well for the `$app/env` import but then the `userEvent.click`, `userEvent.type` were broken.

We've read #304 issue and tried to fork and upgrade `@testing-framework/dom` to 8.10.1 into svelte-testing-library but without success.

Suggested solution:
Unfortunately at this point I have no idea.

**Comment by ph-fritsche** [comment] 2021-11-30 11:42
The exported modules look correct and work in other setups.
In `13.5.0` the exports of `dist/index.js` is:
https://unpkg.com/browse/@testing-library/user-event@13.5.0/dist/index.js
```js
{
  __esModule: true,
  specialChars: { /* ... */ },
  default: {
   click: require("./click").click,
   /* ... */
  }
}
```

The screenshot above shows the following log which might be the result of an incorrect reexport/import.
Could it be that you ran a transpiler on the package in `node_modules`?
```js
{
  __esModule: true,
  default: {
    specialChars: { /* ... */ },
    default: {
       click: require("./click").click,
       /* ... */
    }
  }
}
```

**Comment by ph-fritsche** [comment] 2021-12-30 07:48
Resolved in [v14.0.0-beta.4](https://github.com/testing-library/user-event/releases/tag/v14.0.0-beta.4).

**Closed by ph-fritsche** 2021-12-30 07:48 UTC
Labels: released on @beta

**Comment by mpiorowski** [comment] 2022-01-02 08:38
@ph-fritsche  Got the same error, event with v14.0.0-beta-4, also using --experimental-vm-modules with sveltekit

**Comment by ph-fritsche** [comment] 2022-01-02 09:20
Please, always use the latest version: Currently this is `v14.0.0-beta.6`.

@mpiorowski Could you provide more information please? A reproduction example maybe?
`v14.0.0-beta.4` only contained bundled ESM so the exact error described above is impossible with that version.

**Comment by Josephaberry54** [comment] 2022-01-10 10:08
I get the same error for userEvent.type. Tried v14.0.0-beta-7, also using jest v27.4.7 with --experimental-vm-modules and jsdom test environment in a very simple vanilla js frontend.

**Comment by ph-fritsche** [comment] 2022-01-10 10:15
@Josephaberry54 Could you link to a reproduction so that we can examine the environment?

**Comment by vladimir-el** [comment] 2022-01-11 10:45
I confirm, 14.0.0-beta-4 is working, but 14.0.0-beta-5,6,7 cause the original error to reappear.
I'm using latest stable jest with --experimental-vm-modules

**Comment by ph-fritsche** [comment] 2022-01-20 12:06
@vladimir-el Could you create a reproduction of the environment showcasing this?

**Comment by ph-fritsche** [comment] 2022-02-18 11:22
@illright Thanks for the reproduction example.
At first glance this looks like a problem with the environment.
Our `package.json` includes:
```json
  "main": "./dist/index.cjs",
  "module": "./dist/index.mjs",
  "exports": {
    ".": {
      "require": "./dist/index.cjs",
      "default": "./dist/index.mjs"
    }
  },
```
`import userEvent from '@testing-library/user-event'` should be resolved to `node_modules/@testing-library/user-event/dist/index.mjs`.
But it imports `index.cjs`, as you can see e.g. by simply adding a `console.warn` to that file.
