### ISSUE TITLE
Unit test works with mouseinput but not keyboard input.

### ISSUE THREAD

**Issue by RobinKuenzel** [testing-library/user-event#835] opened 2022-01-16 19:28 UTC
Hello, I'm not sure if this is a bug but I can't figure it out from looking at the documentation. I'd appreciate any input. Please see the attached sandbox for an example of the issue.

- `@testing-library/user-event` version: latest

- Testing Framework and version: jest 20.0.4
- DOM Environment: react-dom 16.3.1

Relevant code or config
Code sandbox illustrating issue: 
https://codesandbox.io/s/floral-resonance-z2h43?file=/src/SelectExample.spec.tsx

What you did:
Using a blueprint select ( https://blueprintjs.com/docs/#select ) and writing unit tests for it. 
The select itself works (mouse and keyboard).
The mouseinput test works.
The keyboard test doesn't work.
I've tried to focus() or target various (parent)Elements but that didn't help either. userEvent.type() targeting the desired item would work but only because the implementation already clicks it, regardless of the keyboard input.

What happened:
No attempt to interact with the opened select via keyboard works (ONLY in unit tests. It works fine for user interaction)

Reproduction repository:
https://codesandbox.io/s/floral-resonance-z2h43

Problem description:
Keyboard interaction in unit doesn't work as expected.

Suggested solution:
Clarifiy in documentation how userEvent should work here (unless it actually doesn't work at all). 
https://testing-library.com/docs/ecosystem-user-event/
https://testing-library.com/docs/dom-testing-library/api-events/

**Comment by ph-fritsche** [comment] 2022-01-18 21:16
This looks like a duplicate of #786 .

**Closed by ph-fritsche** 2022-01-18 21:16 UTC

**Comment by RobinKuenzel** [comment] 2022-01-19 09:26
Hello. Thanks for replying, I saw the other issue but thought it wouldn't apply as that one is using a select element.
Unofrtunately I also don't get what the suggested solution is.
Changing the bracket style doesn't make the testcase in my sandbox work (I had tried that before in fact, the commented out attempts in SelectExample.spec.ts are only a tiny subset of things I tried).

**Comment by ph-fritsche** [comment] 2022-01-19 10:00
@RobinKuenzel Oh it doesn't use a native select. Then it works.
Fixed the test here: https://codesandbox.io/s/magical-archimedes-r2bpq?file=/src/SelectExample.spec.tsx

**Comment by RobinKuenzel** [comment] 2022-01-19 10:27
I think I was missing the tab(). Thank you very much.
