### ISSUE TITLE
form submission not working

### ISSUE THREAD

**Issue by bigfoot31** [testing-library/user-event#401] opened 2020-07-14 09:22 UTC
at the moment if use userEvent.click on an element of type submit, it is not triggering the form submission, neither does fireEvent.click, it may be form implementation that is not using the onClick, however, the input is of submit type and as such, for a real user, clicking on the button does trigger a form submission. I think userEvent.click should trigger a form submission... Great library nonetheless! Thanks!

_Originally posted by @telpochyaotl in https://github.com/testing-library/user-event/issues/20#issuecomment-625315539_

**Comment by marcosvega91** [comment] 2020-07-14 18:56
Hi @bigfoot31 thanks for opening this issue :)

I have created a repo [here](https://codesandbox.io/s/form-submission-63zp5) but I'm not facing any problem. 
Are you doing something different?

**Comment by bigfoot31** [comment] 2020-07-22 04:52
Finally got it to work. Problem was using old versions of @testing-library/react & @testing-library/user-event.

Simply doing `npm i @testing-library/react` was installing older versions of the library.

**Comment by marcosvega91** [comment] 2020-07-22 05:20
I'm happy to hear that. I'm closing the issue 😀

**Closed** 2020-07-22 05:19 UTC
Labels: accuracy, bug, help wanted, needs investigation

**Comment by BackEndTea** [comment] 2022-05-31 15:31
This is kind of a necro bump, but it looks like this issue got re introduced in v 14 of this library, in combination with react 18

**Comment by ph-fritsche** [comment] 2022-06-01 07:43
@BackEndTea Whatever you experienced using `user-event@v14` with `React@18`, I'm sure it has nothing to do with something missing in earlier versions of `@testing-library/react` that according to the comments above was already a non-issue at the time this issue was created.

If you think there is a bug on our end, please help us improve by creating a reproduction and [filing a new bug report](https://github.com/testing-library/user-event/issues/new?assignees=&labels=needs+assessment%2Cbug&template=bug_report.yml).

If you don't know what is wrong with your test, please help others who might run into the same problem by creating a reproduction and [opening a Discussion](https://github.com/testing-library/user-event/discussions/new?category=q-a).
