### ISSUE TITLE
user.type does not trigger validations for "minlength"

### ISSUE THREAD

**Issue by KonnorRogers** [testing-library/user-event#1221] opened 2024-05-23 00:35 UTC
### Reproduction example

https://codesandbox.io/p/devbox/pm73nz?file=%2Fsrc%2Findex.test.jsx%3A25%2C1

### Prerequisites

1. Render an `<input minlength="10">` element.
2. Setup user-event
3. do `input.focus(); await user.type("{1}{2}{3}")`
4. Expect `input.validity.tooShort` to be true, expect `input.validationMessage` to not be an empty string. Basically, expect it to trigger native constraint validation

### Expected behavior

Expect behavior:

When typing `123` into a `<input minlength="10">` I expect native constraint validation to be trigger.

https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/tooShort
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/minlength

### Actual behavior

Native constraint validation never triggers

### User-event version

14.5.2

**Comment by ph-fritsche** [comment] 2024-06-03 10:34
Closing this as duplicate of #801 .

**Closed by ph-fritsche** 2024-06-03 10:34 UTC
Labels: bug, needs assessment
