### ISSUE TITLE
userEvent.upload can't pass validation if the input element is `required`

### ISSUE THREAD

**Issue by ysgk** [testing-library/user-event#1106] opened 2023-03-12 08:08 UTC
### Reproduction example

https://codesandbox.io/s/determined-dan-emcumz?file=/src/App.test.js

### Prerequisites

1. Render `<input type="file" required />` element.
1. `userEvent.upload()` a file to it.

### Expected behavior

userEvent.upload should pass valueMissing constraint.

### Actual behavior

Validation fails due to valueMissing constraint. Consequently, forms that contain a `required` file input cannot be submitted using userEvent.

### User-event version

14.4.3

**Comment by ph-fritsche** [comment] 2023-03-14 08:47
Closing this as duplicate of #801 .

**Closed by ph-fritsche** 2023-03-14 08:47 UTC
Labels: bug, needs assessment
