### ISSUE TITLE
Problem with using v14 for keyboard behaviour to replicate pressing tab in the browser

### ISSUE THREAD

**Issue by kksy** [testing-library/user-event#1018] opened 2022-08-03 10:37 UTC
### Reproduction example

https://codesandbox.io/s/ecstatic-rubin-yygg77?file=/src/App.spec.js

### Prerequisites

1. Go to the codesandbox link and press the "Test" tab

### Expected behavior

Button element should have focus. This works when using version 13.5.0 `userEvent.tab()`

### Actual behavior

Button does not have focus or is not the active element in the page

### User-event version

14.4.1

### Environment

Testing Library framework: `@testing-library/react@13.3.0`

JS framework:  `react@18.0.0` 

Test environment: `jest sandbox version`

DOM implementation: `jsdom sandbox version`

### Additional context

I believe that this missing feature prevents us from testing keyboard accessibility in an easy way

**Comment by ph-fritsche** [comment] 2022-08-03 10:41
Looks like a duplicate of #1002

**Comment by kksy** [comment] 2022-08-04 07:43
I've just realised the implementation of tab is using the keyboard API under the hood. You're right @robinh-jsx. I tried it again locally and `userEvent.tab()` works in 13.5.0 and 14.3.0. `userEvent.keyboard('{Tab}')` never worked with focus event at 13.5.0 though.

According to the documentation, it also _implies_ that both the `keyboard` and `tab` should work the same  
![Screenshot 2022-08-04 at 09 41 08](https://user-images.githubusercontent.com/10233535/182792007-20fb4e7d-22a8-4e8e-8400-226d243c32a8.png)

**Comment by ph-fritsche** [comment] 2022-08-04 07:50
@kksy fixed your test: https://codesandbox.io/s/flamboyant-liskov-kcccjd?file=/src/App.spec.js
Working as expected

**Comment by ph-fritsche** [comment] 2022-08-04 07:53
> Works for me in 14.3.0 Broken in 14.4.0+

@robinh-jsx Could you provide more information, maybe a reproduction example? There was no particular change to either handling of `Tab` or how an element was focused. Might be unrelated.

**Comment by kksy** [comment] 2022-08-04 08:02
Thanks @ph-fritsche I completely missed the Promise return. Regarding @robinh-jsx comment, `user.tab`  works without `await` in 14.3.0, but you need `await` in 14.4.0

**Comment by ph-fritsche** [comment] 2022-08-04 08:21
All APIs in `v14` return a Promise.
fixed in https://github.com/testing-library/testing-library-docs/pull/1128

**Comment by ph-fritsche** [comment] 2022-08-04 08:21
@all-contributors add @kksy docs

**Closed** 2022-08-04 08:22 UTC
Labels: bug, needs assessment
